#### POD Single Unit, contains multiple containers. Has unique POD IP
## filename: pod1.yml
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: mahendra
  labels:
    name: app1
spec:
  containers:
  - name: myapp
    image: mahendrshinde/myweb:1
    resources:
      limits:
        memory: "64Mi"
        cpu: "200m"
    ports:
      - containerPort: 80
## Command to deploy
# $ kubectl apply -f pod1.yml
## Verify the pod
# $ kubectl get po -n mahendra
# $ kubectl describe -f pod1.yml
